### ISSUE TITLE
Getting error after installation

### ISSUE THREAD

**Issue by aneena-thomas** [abbasfreestyle/react-native-af-video-player#155]
Got the below error after use
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-06-02 at 13 15 22](https://user-images.githubusercontent.com/13118654/120443854-aed24200-c3a4-11eb-8e53-dbc64f378db0.png)
@

**Comment by vikrant-kukadiya** [comment]
@aneena-thomas  Please follow the below steps..... That works for me.

1) yarn add react-native-video // npm install react-native-video
1) remove line no. 10 "react-native-video": "^2.0.0"  from node_modules/react-native-af-video-player/package.json
2) Remove  complete folder react-native-video from path /node_modules/react-native-af-video-player/node_modules/
4) Try to run application. It started working.

Note: So, The problem is library conflicting react-native-video versions. The library has used react-native-video 2.3.1 however the latest one is 5.1.1

Solution: You can form this library and change the react-native-video version to 5.1.1 at package.json and use that in your application.

Let me know if that not working for you..... Thanks :)

**Comment by aneena-thomas** [comment]
Hi @vikrant-k-simformsolutions  thanks for the reply, its working thank you.

**Comment by sraza295** [comment]
> 

Thanks bro.
You saved my day
