### ISSUE TITLE
inline issues after toggling from full screen

### ISSUE THREAD

**Issue by assafb81** [abbasfreestyle/react-native-af-video-player#18]
Hi @abbasfreestyle,

1. Sometimes when toggling from full screen to inline I see black bars above and below the video, as if the video does not fill the entire videoContainer.
2. The video container not always returning to inline, as if the height of the container does not update in time :(

Did you encounter this issues?
I have to say I did not use the package as `blackBox` but used parts of it and change few things - like icons, video cover, error etc.

**Comment by abbasfreestyle** [comment]
Hi @assafb81 do you have images/videos + code to demonstrate your issue?

**Comment by assafb81** [comment]
See this screen shot, when clicking play the video is acctually take part of its container: 
![image](https://user-images.githubusercontent.com/28925534/37582298-fec030f6-2b54-11e8-9873-567fa3e6086c.png)

the relevant code is:
```
<View style={isFullScreen
                ? [styles.fullScreen, { height }]
                : [styles.background, containerStyle, { height }, styles.inline]}
>
    <Video
    style={isFullScreen
            ? [styles.fullScreen, { height }]
            : [{ height }, styles.inline]}
            .....
    />
</View>
```
the relevant style classes are:
```
background: {
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
},
inline: {
    alignSelf: 'stretch',
},
fullScreen: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    zIndex: 4,
},
containerStyle: {
    marginLeft: 30,
    marginRight: 30,
    marginTop: '20%',
},

```

**Comment by assafb81** [comment]
@abbasfreestyle 
why did you close this. 
I added the code as you can see above and also image.
I will refine the issue:

when the `videoContainer` class contain the following:
```
marginLeft: 30,
marginRight: 30,
```

I can see the black bars. 
I am adding the margin because I want to place the video element when inline in the center of the screen and not spread on the entire width of the screen.
When I remove the `marginLeft` and `marginRight` the issue is solved **but** the video is not in the center of the screen and its spread on the entire width of the screen.

**Comment by abbasfreestyle** [comment]
@assafb81,

I closed this issue assuming it was resolved with the code you used.

Standard video ratios are 16:9 which is why the video height is multiplied by 0.562. Videos with these ratios should never see black bars inline in theory. With the different videos I've used I've never had seen black bars until I use a video with a unique ratio.

It looks like you're trying to display the entire content of a video where the ratio is not 16:9, naturally you'll either see black bars or need to zoom to cover the player. You've applied a specific height and added marginHorizontal: 30 outside the scope of the video player and quoting from the readme:

> Avoid adding alignItems: 'center' to the container, it can cause fullscreen mode to disappear :D

Perhaps you may want to re-consider your container styling.

However, if your video is 16:9 this could be an issue related to react-native-video. Maybe it might be worth looking at the issues in that module.
