### ISSUE TITLE
Better seek support

### ISSUE THREAD

**Issue by LimaEduardo** [abbasfreestyle/react-native-af-video-player#46]
Hello everyone!

I'm trying to use seek, but it's not working so well. 

On the first try, i simply tried to use seek this way.

```javascript
<Video 
    url={props.video.signedUrl}
    title={props.video.title}
    ref={(ref) => {this.video = ref}}
    onFullScreen={status => this.onFullScreen(status)}
    rotateToFullScreen
/>

<Button onPress={() => this.video.seek(20)}> seek </Button>
```

But when i do this, the player go to a very high (above the duration) number of seconds, so i tried to see the implementation to understand what was going on and i saw this:

```javascript
 seek(val) {
    const currentTime = val * this.state.duration
    this.setState({ seeking: true, currentTime })
  }
```

I confess that i don't understand why multiply val by duration of video. So i tried to make a modification and use react-native-video seek

```javascript
 seek(val) {
    const currentTime = val * this.state.duration
    this.player.seek(val)
    this.setState({ seeking: true, currentTime })
  }
```

Worked in some way. On click, i was able to seek the video though the expected time, but the timer in controls got stucked in this expected time.

So, i'm missing something? I went wrong somewhere? How do i properly seek?

Thanks in advance and congratulations on this work, this is the best react-native player that i worked so far :smile: 

- react-native-af-video-player version: 0.1.9
- react-native version: 0.48.3
- Android 8.0 via Android Virtual Device

**Comment by abbasfreestyle** [comment]
Hi @LimaEduardo,

Thanks for the kind words :)
To give you a bit of context to seek(), the value is actually the slider percentage. so you'd need to convert that into seconds, which is why you see `val * this.state.duration` i'll rename it to `percent * this.state.duration` in the next release.

I haven't actually tested controlling seek from outside. But if you covert the seconds into percentage, in theory it should work. You'd need the duration in order to work out the percentage. To do that you can access the the duration with onLoad.

e.g

```js
<Video 
    url={props.video.signedUrl}
    title={props.video.title}
    ref={(ref) => {this.video = ref}}
    onFullScreen={status => this.onFullScreen(status)}
    onLoad={(data) => this.setState({ duration: data.duration })
    rotateToFullScreen
/>

<Button onPress={() => this.video.onSeekRelease(20 / this.state.duration)}> seek </Button>
```

I hope this solves your issue. I'll add better seek control in the next version without having to calculate the percentage, something like seekTo(seconds).

**Comment by abbasfreestyle** [comment]
@LimaEduardo I've added seekTo(seconds) in version 0.2.0 👍

**Comment by LimaEduardo** [comment]
It's working just fine! Thanks :smile:
